{% set data = load_setuptools()%}
package:
  name: binstar-build
  version: {{ data.get('version') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - binstar
    - setuptools
    - psutil
    - pywin32 [win]

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
